# Generated by Django 4.2.5 on 2023-10-28 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Second_Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=200)),
                ('Linkedin_Profile', models.CharField(max_length=500)),
                ('Github_Profile', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reqruipment_Title', models.CharField(max_length=200)),
                ('Year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Applications.year')),
            ],
        ),
    ]
