# Generated by Django 4.2.5 on 2023-10-28 13:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date_Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('Reqruipment_Title', models.CharField(max_length=200)),
                ('Year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Applications.year')),
            ],
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
