# Generated by Django 4.2.5 on 2023-10-28 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0002_date_application_delete_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date_application',
            name='Date',
        ),
        migrations.AddField(
            model_name='date_application',
            name='from_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='date_application',
            name='to_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
