# Generated by Django 4.2.6 on 2023-10-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0003_remove_date_application_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='Twitter_Profile',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='job_role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
